services:
  guacd:
    image: guacamole/guacd:1.6.0
    restart: unless-stopped
    volumes:
      - ./recordings:/var/lib/guacamole/recordings

  guacamole:
    image: guacamole/guacamole:1.6.0
    depends_on:
      - guacd
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      WEBAPP_CONTEXT: ROOT
      OPENID_ENABLED: "true"
      OPENID_AUTHORIZATION_ENDPOINT: "https://login.microsoftonline.com/${ENTRA_TENANT_ID}/oauth2/v2.0/authorize"
      OPENID_JWKS_ENDPOINT: "https://login.microsoftonline.com/${ENTRA_TENANT_ID}/discovery/v2.0/keys"
      OPENID_ISSUER: "https://login.microsoftonline.com/${ENTRA_TENANT_ID}/v2.0"
      OPENID_CLIENT_ID: "${OPENID_CLIENT_ID}"
      OPENID_REDIRECT_URI: "${OPENID_REDIRECT_URI}"
      QUICKCONNECT_ENABLED: "true"
      RECORDING_ENABLED: "true"
      QUICKCONNECT_DEFAULT_SECURITY: "nla"
      QUICKCONNECT_DEFAULT_IGNORE_CERT: "true"
      QUICKCONNECT_DEFAULT_ENABLE_FONT_SMOOTHING: "true"
    volumes:
      - ./recordings:/var/lib/guacamole/recordings
      - ./quickconnect-recording-defaults/target/quickconnect-recording-defaults-1.6.0.jar:/etc/guacamole/extensions/quickconnect-recording-defaults-1.6.0.jar:ro
